spring:
  application:
    name: validator
  profiles:
    active: local

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id}:${server.port}

endpoints:
  restart:
    enabled: true

logging:
  file: validator-service.log
---
# profile for development
spring:
  profiles: development

server:
  port: 1234

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
# for local deployment of all services
spring:
  profiles: local

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
---
# for use in aws
spring:
  profiles: aws

server:
  port: 0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://ec2-52-28-94-178.eu-central-1.compute.amazonaws.com:8761/eureka/