spring:
  application:
    name: validator-service

# dynamic port
#server:
#  port: 0

# for development
server:
  port: 4321


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
