spring:
  application:
    name: pmd
  profiles:
    active: development

logging:
  file: pmd-service.log

app:
  config:
    svn:
      ip: 141.37.122.26
    pmd:
      ruleset:  java-basic,java-design,java-codesize,java-optimizations,java-unnecessary,java-braces
---
# profile for development
spring:
  profiles: development

server:
  port: 1234

eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
# for local deployment of all services
spring:
  profiles: local

server:
  port: 0

eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true

---

---
# for use in aws
spring:
  profiles: aws

server:
  port: 0

eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true