spring:
  application:
    name: config
  cloud:
      config:
        server:
          git:
            uri: https://github.com/htwg-cloud-application-development/config-repo
            basedir: target/config

server:
  port: 8888

