spring:
  application:
    name: config
  cloud:
      config:
        server:
          git:
            uri: https://github.com/T1m1/config-repo
            basedir: target/config

server:
  port: 8888

