spring:
  application:
    name: edgeserver

server:
  port: 1111

zuul:
  routes:
    validator-service:
      path: /validator-service/**
  host:
    socket-timeout-millis: 200000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 200000

ribbon:
  ReadTimeout: 200000

---
spring:
  profiles: local

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---

spring:
  profiles: aws

eureka:
  instance:
    hostname: ec2-52-58-161-190.eu-central-1.compute.amazonaws.com
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${eureka.instance.hostname:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://ec2-52-29-21-217.eu-central-1.compute.amazonaws.com:8761/eureka/


