# dynamic port
#server:
#  port: 0

spring:
  data:
    mongodb:
      host: localhost
      port: 27017

# for development
server:
  port: 1234


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
